### ISSUE TITLE
Getting error 'sharedApplication' is unavailable: not available on iOS (App Extension) - Use view controller based solutions where appropriate instead.

### ISSUE THREAD

**Issue by atulaccedo** [swisspol/GCDWebServer#414]
Cannot use GCDWebServer in my app. Receiving error:

> 'sharedApplication' is unavailable: not available on iOS (App Extension) - Use view controller based solutions where appropriate instead.

on this line:

`[[UIApplication sharedApplication] beginBackgroundTaskWithExpirationHandler...`

**Comment by swisspol** [comment]
Should be fixed by #416

**Comment by atulaccedo** [comment]
Still not fixed. Just cross-checked that the merge request is also reverted.

**Comment by swisspol** [comment]
Yes this is not fixed and is not fixable because there’s no compiler define that can be used to detect compiling for extensions.

**Comment by derrickshowers** [comment]
What if you do something like checking for the selector on `UIApplication`?

Example:
```
+ (nullable UIApplication *)sharedApplicationHelper {
    if ([UIApplication respondsToSelector:@selector(sharedApplication)]) { 
        return [UIApplication performSelector:@selector(sharedApplication)]; 
    }
    return nil;
}
```

Let me know your thoughts. I can open a PR...
